theme="catppuccin_macchiato"

[editor]
line-number="relative"
true-color=true
end-of-line-diagnostics="hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"

[editor.soft-wrap]
enable = true
max-wrap = 80
max-indent-retain = 0

[keys.normal]
esc=["collapse_selection","keep_primary_selection"]
A-k=["delete_selection","move_line_up","paste_before"]
A-j=["delete_selection","paste_after"]
