[tools]
### most used
helix = "latest"
lazygit = "latest"
yazi = "latest"
zellij = "latest"
bat = "latest"

### nice to have
difftastic = "latest"
fd = "latest"
glow = "latest"
starship = "latest"
jq = "latest"
make = "latest"

### GO
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint-langserver = "latest"
golangci-lint = "latest"
"go:github.com/mhersson/mpls" = "latest"
"go:github.com/antonmedv/fx" = "latest"

### Nodejs
node = "latest"
pnpm = "latest"

### rust
rust = "latest"
"cargo:lsp-ai" = "latest"

### zig
zig = "latest"
zls = "latest"

[settings]
experimental = true
